"""Prompt constants for HyperHiGraAgent."""

from .prompts import (
    ENTITY_EXTRACTION_PROMPT,
    QA_ADAPTIVE_PROMPT,
    QA_SINGLE_STEP_PROMPT,
    QUESTION_CLARIFICATION_PROMPT,
    QUESTION_DECOMPOSITION_PROMPT,
    SUFFICIENCY_CHECK_PROMPT,
)

__all__ = [
    "QUESTION_CLARIFICATION_PROMPT",
    "QUESTION_DECOMPOSITION_PROMPT",
    "SUFFICIENCY_CHECK_PROMPT",
    "QA_SINGLE_STEP_PROMPT",
    "QA_ADAPTIVE_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
]
